import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Navbar from '../components/Navbar';
import '../styles/Auth.css';

/**
 * Production-Grade Enterprise Registration Component
 * Customized for Bugema University IT Support System
 * 
 * Features:
 * - Bugema University-specific validation
 * - Student ID format validation (22/BIT/BU/R/0010)
 * - Department and course mapping
 * - Campus-specific validation
 * - Enhanced security for university environment
 * 
 * @version 2.1.0
 * @author Bugema University IT Support Team
 */

const Register = () => {
  // Main form state
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: '',
    role: 'student',
    department: '',
    program: '', // Specific program/course
    campus: 'main', // Default to main campus
    studentId: '',
    phone: '',
    yearOfEntry: new Date().getFullYear().toString().slice(-2), // Last 2 digits of current year
    status: 'R', // R for Regular, H for In-service
    agreeToTerms: false,
    receiveNotifications: true
  });

  // Component state
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [validationErrors, setValidationErrors] = useState({});
  const [passwordStrength, setPasswordStrength] = useState(0);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [formProgress, setFormProgress] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGeneratedStudentId, setAutoGeneratedStudentId] = useState('');

  const nameRef = useRef(null);
  const { register, logSecurityEvent } = useAuth();
  const navigate = useNavigate();

  // Bugema University Configuration
  const UNIVERSITY_NAME = 'Bugema University';
  const UNIVERSITY_EMAIL_DOMAINS = ['@bugemauniv.ac.ug', '@student.bugemauniv.ac.ug'];
  const CURRENT_YEAR = new Date().getFullYear().toString().slice(-2);

  // Bugema University Campuses
  const campuses = [
    { value: 'main', label: 'Main Campus (Luwero)', code: 'BU' },
    { value: 'kampala', label: 'Kampala Campus', code: 'KLA' },
    { value: 'australia', label: 'Australia Campus', code: 'AUS' },
    { value: 'nairobi', label: 'Nairobi Campus', code: 'NRB' },
    { value: 'kigali', label: 'Kigali Campus', code: 'KGL' }
  ];

  // Bugema University Programs/Courses with departments
  const programs = [
    // School of Computing and Informatics
    { value: 'bit', label: 'Bachelor of Information Technology', department: 'computing', code: 'BIT' },
    { value: 'bcs', label: 'Bachelor of Computer Science', department: 'computing', code: 'BCS' },
    { value: 'dbit', label: 'Diploma in Information Technology', department: 'computing', code: 'DBIT' },
    
    // School of Business
    { value: 'bba', label: 'Bachelor of Business Administration', department: 'business', code: 'BBA' },
    { value: 'bacco', label: 'Bachelor of Accounting', department: 'business', code: 'BACCO' },
    { value: 'bmgt', label: 'Bachelor of Management', department: 'business', code: 'BMGT' },
    
    // School of Education
    { value: 'bed', label: 'Bachelor of Education', department: 'education', code: 'BED' },
    { value: 'bed_arts', label: 'Bachelor of Education (Arts)', department: 'education', code: 'BED-A' },
    { value: 'bed_sci', label: 'Bachelor of Education (Science)', department: 'education', code: 'BED-S' },
    
    // School of Theology
    { value: 'bth', label: 'Bachelor of Theology', department: 'theology', code: 'BTH' },
    { value: 'mdiv', label: 'Master of Divinity', department: 'theology', code: 'MDIV' },
    
    // School of Health Sciences
    { value: 'bn', label: 'Bachelor of Nursing', department: 'health', code: 'BN' },
    { value: 'bpharm', label: 'Bachelor of Pharmacy', department: 'health', code: 'BPHARM' },
    
    // Postgraduate
    { value: 'mba', label: 'Master of Business Administration', department: 'postgraduate', code: 'MBA' },
    { value: 'mcs', label: 'Master of Computer Science', department: 'postgraduate', code: 'MCS' },
    { value: 'mphil', label: 'Master of Philosophy', department: 'postgraduate', code: 'MPHIL' },
    { value: 'phd', label: 'Doctor of Philosophy', department: 'postgraduate', code: 'PHD' }
  ];

  // Departments for non-students
  const departments = [
    { value: 'computing', label: 'School of Computing and Informatics' },
    { value: 'business', label: 'School of Business' },
    { value: 'education', label: 'School of Education' },
    { value: 'theology', label: 'School of Theology' },
    { value: 'health', label: 'School of Health Sciences' },
    { value: 'administration', label: 'University Administration' },
    { value: 'finance', label: 'Finance Department' },
    { value: 'registry', label: 'Academic Registry' },
    { value: 'library', label: 'University Library' },
    { value: 'it_services', label: 'IT Services Department' },
    { value: 'facilities', label: 'Facilities Management' },
    { value: 'security', label: 'Security Department' }
  ];

  // Role options for Bugema University
  const roleOptions = [
    {
      value: 'student',
      label: 'Student',
      description: 'Current student of Bugema University',
      icon: '🎓',
      permissions: ['create_ticket', 'view_own_tickets', 'access_knowledge_base', 'view_announcements'],
      requiresApproval: false,
      showStudentFields: true
    },
    {
      value: 'lecturer',
      label: 'Lecturer/Instructor', 
      description: 'Teaching staff and instructors',
      icon: '👨‍🏫',
      permissions: ['create_ticket', 'view_department_tickets', 'access_knowledge_base', 'manage_course_content'],
      requiresApproval: true,
      showStudentFields: false
    },
    {
      value: 'staff',
      label: 'Administrative Staff',
      description: 'Non-teaching administrative staff',
      icon: '👨‍💼',
      permissions: ['create_ticket', 'view_department_tickets', 'access_knowledge_base', 'manage_documents'],
      requiresApproval: true,
      showStudentFields: false
    },
    {
      value: 'technician',
      label: 'IT Technician',
      description: 'IT support and technical staff',
      icon: '👨‍💻',
      permissions: ['view_all_tickets', 'resolve_tickets', 'manage_assets', 'access_admin_tools'],
      requiresApproval: true,
      showStudentFields: false
    },
    {
      value: 'admin',
      label: 'System Administrator',
      description: 'Full system access and user management',
      icon: '🔧',
      permissions: ['all_permissions'],
      requiresApproval: true,
      showStudentFields: false
    }
  ];

  // Student status options
  const studentStatusOptions = [
    { value: 'R', label: 'Regular Student', description: 'Full-time on-campus student' },
    { value: 'H', label: 'In-service/Distance', description: 'Part-time or distance learning student' },
    { value: 'E', label: 'Evening Student', description: 'Evening program student' },
    { value: 'W', label: 'Weekend Student', description: 'Weekend program student' }
  ];

  // Auto-focus first input on mount
  useEffect(() => {
    if (nameRef.current) {
      nameRef.current.focus();
    }
  }, []);

  // Calculate form progress
  useEffect(() => {
    calculateFormProgress();
  }, [formData]);

  // Calculate password strength
  useEffect(() => {
    if (formData.password) {
      calculatePasswordStrength(formData.password);
    } else {
      setPasswordStrength(0);
    }
  }, [formData.password]);

  // Auto-generate student ID when program, campus, or year changes
  useEffect(() => {
    if (formData.role === 'student' && formData.program && formData.campus) {
      generateStudentIdPreview();
    }
  }, [formData.program, formData.campus, formData.yearOfEntry, formData.status]);

  /**
   * Generates a preview of student ID based on selected options
   */
  const generateStudentIdPreview = () => {
    const programObj = programs.find(p => p.value === formData.program);
    const campusObj = campuses.find(c => c.value === formData.campus);
    
    if (programObj && campusObj) {
      const year = formData.yearOfEntry || CURRENT_YEAR;
      const programCode = programObj.code;
      const campusCode = campusObj.code;
      const statusCode = formData.status || 'R';
      
      // Generate a temporary unique number (will be replaced by server)
      const tempUnique = Math.floor(Math.random() * 9000 + 1000).toString();
      
      const previewId = `${year}/${programCode}/${campusCode}/${statusCode}/${tempUnique}`;
      setAutoGeneratedStudentId(previewId);
    }
  };

  /**
   * Validates Bugema University email format
   */
  const validateEmail = (email) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    
    if (!emailRegex.test(email.trim())) {
      return 'Please enter a valid email address';
    }

    // Check for Bugema University domain
    const isUniversityEmail = UNIVERSITY_EMAIL_DOMAINS.some(domain => 
      email.toLowerCase().endsWith(domain.toLowerCase())
    );

    if (!isUniversityEmail) {
      return `Please use your Bugema University email address (${UNIVERSITY_EMAIL_DOMAINS.join(' or ')})`;
    }

    return null;
  };

  /**
   * Validates Bugema University student ID format
   */
  const validateStudentId = (studentId) => {
    if (formData.role !== 'student') return null;
    
    if (!studentId.trim()) {
      return 'Student ID is required for student accounts';
    }
    
    // Bugema University Student ID format: 22/BIT/BU/R/0010
    const studentIdRegex = /^(\d{2})\/([A-Z]{2,6})\/([A-Z]{2,3})\/([A-Z])\/(\d{4})$/;
    const match = studentId.trim().match(studentIdRegex);
    
    if (!match) {
      return 'Invalid Student ID format. Use format: YY/PROGRAM/CAMPUS/STATUS/NUMBER (e.g., 22/BIT/BU/R/0010)';
    }
    
    const [_, year, program, campus, status, number] = match;
    
    // Validate year (should be reasonable)
    const currentYear = parseInt(CURRENT_YEAR);
    const entryYear = parseInt(year);
    
    if (entryYear < 10 || entryYear > currentYear) {
      return `Invalid entry year. Should be between 10 and ${currentYear}`;
    }
    
    // Validate program code exists
    const validProgram = programs.find(p => p.code === program);
    if (!validProgram) {
      return `Invalid program code. Valid codes: ${programs.map(p => p.code).join(', ')}`;
    }
    
    // Validate campus code exists
    const validCampus = campuses.find(c => c.code === campus);
    if (!validCampus) {
      return `Invalid campus code. Valid codes: ${campuses.map(c => c.code).join(', ')}`;
    }
    
    // Validate status code
    const validStatus = studentStatusOptions.find(s => s.value === status);
    if (!validStatus) {
      return `Invalid status code. Valid codes: ${studentStatusOptions.map(s => s.value).join(', ')}`;
    }
    
    // Validate unique number (should be 4 digits)
    if (number.length !== 4 || parseInt(number) === 0) {
      return 'Invalid unique number. Should be 4 digits (0001-9999)';
    }
    
    return null;
  };

  /**
   * Validates phone number for Uganda format
   */
  const validatePhone = (phone) => {
    if (!phone.trim()) return null;
    
    // Remove all non-digit characters
    const cleanedPhone = phone.replace(/[\s\-\(\)\.]/g, '');
    
    // Uganda phone number validation
    const ugandaPhoneRegex = /^(?:256|0)(7[0-9]{8})$/;
    
    if (!ugandaPhoneRegex.test(cleanedPhone)) {
      return 'Please enter a valid Ugandan phone number (e.g., 07xxxxxxxx or 2567xxxxxxxx)';
    }
    
    return null;
  };

  /**
   * Validates username
   */
  const validateUsername = (username) => {
    if (!username.trim()) {
      return 'Full name is required';
    }
    
    if (username.length < 2) {
      return 'Name must be at least 2 characters';
    }
    
    // Allow international names with various characters
    const nameRegex = /^[A-Za-zÀ-ÖØ-öø-ÿ\s\-\'\.]+$/;
    if (!nameRegex.test(username)) {
      return 'Name can only contain letters, spaces, hyphens, apostrophes, and periods';
    }
    
    return null;
  };

  /**
   * Validates program/course selection
   */
  const validateProgram = (program) => {
    if (formData.role === 'student' && !program) {
      return 'Please select your program/course';
    }
    return null;
  };

  /**
   * Validates campus selection
   */
  const validateCampus = (campus) => {
    if (formData.role === 'student' && !campus) {
      return 'Please select your campus';
    }
    return null;
  };

  /**
   * Calculates password strength
   */
  const calculatePasswordStrength = (password) => {
    let strength = 0;
    
    // Length check
    if (password.length >= 8) strength += 25;
    if (password.length >= 12) strength += 10;
    
    // Character variety checks
    if (/[A-Z]/.test(password)) strength += 15;
    if (/[a-z]/.test(password)) strength += 15;
    if (/[0-9]/.test(password)) strength += 15;
    if (/[^A-Za-z0-9]/.test(password)) strength += 15;
    
    // Common patterns penalty
    const commonPatterns = [
      '123456', 'password', 'qwerty', '111111',
      new RegExp(formData.username.toLowerCase()),
      new RegExp(formData.email.split('@')[0].toLowerCase())
    ];
    
    commonPatterns.forEach(pattern => {
      if (typeof pattern === 'string' && password.includes(pattern)) {
        strength -= 20;
      } else if (pattern instanceof RegExp && pattern.test(password)) {
        strength -= 20;
      }
    });
    
    // Ensure strength is between 0 and 100
    strength = Math.max(0, Math.min(100, strength));
    setPasswordStrength(strength);
    
    return strength;
  };

  /**
   * Gets password strength label and color
   */
  const getPasswordStrengthInfo = () => {
    if (passwordStrength < 30) return { label: 'Weak', color: '#ef4444', className: 'weak' };
    if (passwordStrength < 60) return { label: 'Fair', color: '#f59e0b', className: 'fair' };
    if (passwordStrength < 80) return { label: 'Good', color: '#10b981', className: 'good' };
    return { label: 'Strong', color: '#059669', className: 'strong' };
  };

  /**
   * Calculates form completion progress
   */
  const calculateFormProgress = () => {
    const fields = [
      'username', 'email', 'password', 'confirmPassword',
      'role', 'agreeToTerms'
    ];
    
    if (formData.role === 'student') {
      fields.push('program', 'campus', 'yearOfEntry', 'status', 'studentId');
    } else {
      fields.push('department');
    }
    
    let completed = 0;
    
    fields.forEach(field => {
      if (field === 'agreeToTerms') {
        if (formData[field]) completed++;
      } else if (formData[field]?.toString().trim()) {
        completed++;
      }
    });
    
    const progress = Math.round((completed / fields.length) * 100);
    setFormProgress(progress);
  };

  /**
   * Handles input changes with validation
   */
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    // Sanitize input
    let sanitizedValue = value;
    
    switch (name) {
      case 'username':
        sanitizedValue = value.trim();
        break;
      case 'email':
        sanitizedValue = value.trim().toLowerCase();
        break;
      case 'phone':
        // Format phone number as user types
        sanitizedValue = formatPhoneNumber(value);
        break;
      case 'studentId':
        sanitizedValue = value.trim().toUpperCase();
        break;
      case 'yearOfEntry':
        // Only allow 2-digit years
        sanitizedValue = value.replace(/\D/g, '').slice(0, 2);
        break;
      default:
        sanitizedValue = value;
    }
    
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : sanitizedValue
    }));
    
    // Clear field-specific error when user starts typing
    if (validationErrors[name]) {
      setValidationErrors(prev => ({ ...prev, [name]: '' }));
    }
    
    // Clear general error
    if (error) setError('');
  };

  /**
   * Formats Ugandan phone number as user types
   */
  const formatPhoneNumber = (phone) => {
    // Remove all non-digit characters
    const cleaned = phone.replace(/\D/g, '');
    
    // Handle Ugandan format
    if (cleaned.startsWith('256')) {
      const withoutCode = cleaned.slice(3);
      if (withoutCode.length <= 9) {
        return `256 ${withoutCode.slice(0, 3)} ${withoutCode.slice(3, 6)} ${withoutCode.slice(6, 9)}`;
      }
    } else if (cleaned.startsWith('0')) {
      const withoutZero = cleaned.slice(1);
      if (withoutZero.length <= 9) {
        return `0${withoutZero.slice(0, 3)} ${withoutZero.slice(3, 6)} ${withoutZero.slice(6, 9)}`;
      }
    }
    
    return phone;
  };

  /**
   * Validates the entire form
   */
  const validateForm = useCallback(() => {
    const errors = {};
    
    // Validate each field
    errors.username = validateUsername(formData.username);
    errors.email = validateEmail(formData.email);
    errors.phone = validatePhone(formData.phone);
    errors.studentId = validateStudentId(formData.studentId);
    errors.program = validateProgram(formData.program);
    errors.campus = validateCampus(formData.campus);
    
    // Password validation
    if (!formData.password) {
      errors.password = 'Password is required';
    } else if (formData.password.length < 8) {
      errors.password = 'Password must be at least 8 characters';
    } else if (passwordStrength < 30) {
      errors.password = 'Please choose a stronger password';
    }
    
    // Confirm password validation
    if (formData.password !== formData.confirmPassword) {
      errors.confirmPassword = 'Passwords do not match';
    }
    
    // Department validation for non-students
    if (formData.role !== 'student' && !formData.department) {
      errors.department = 'Please select your department';
    }
    
    // Terms agreement validation
    if (!formData.agreeToTerms) {
      errors.agreeToTerms = 'You must agree to the Terms of Service';
    }
    
    // Remove null errors
    Object.keys(errors).forEach(key => {
      if (!errors[key]) delete errors[key];
    });
    
    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  }, [formData, passwordStrength]);

  /**
   * Handles form submission with enhanced security
   */
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setValidationErrors({});
    
    // Validate form
    if (!validateForm()) {
      setError('Please fix the errors in the form');
      return;
    }
    
    setLoading(true);
    setIsSubmitting(true);
    
    try {
      // Log registration attempt
      logSecurityEvent('registration_attempt', {
        email: formData.email,
        role: formData.role,
        program: formData.program,
        campus: formData.campus,
        timestamp: new Date().toISOString()
      });
      
      // Prepare data for registration
      const registrationData = {
        username: formData.username.trim(),
        email: formData.email.trim().toLowerCase(),
        password: formData.password,
        role: formData.role,
        phone: formData.phone ? formData.phone.replace(/\D/g, '') : undefined,
        metadata: {
          registrationTimestamp: new Date().toISOString(),
          userAgent: navigator.userAgent,
          screenResolution: `${window.screen.width}x${window.screen.height}`,
          timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
          institution: UNIVERSITY_NAME
        }
      };
      
      // Add role-specific data
      if (formData.role === 'student') {
        registrationData.studentInfo = {
          studentId: formData.studentId.trim().toUpperCase(),
          program: formData.program,
          campus: formData.campus,
          yearOfEntry: formData.yearOfEntry,
          status: formData.status,
          department: programs.find(p => p.value === formData.program)?.department
        };
      } else {
        registrationData.department = formData.department;
        registrationData.position = formData.role;
      }
      
      console.log('🔐 Registering user at Bugema University:', {
        email: registrationData.email,
        role: registrationData.role,
        studentId: registrationData.studentInfo?.studentId
      });
      
      const result = await register(registrationData);
      
      if (result.success) {
        // Log successful registration
        logSecurityEvent('registration_success', {
          email: formData.email,
          role: formData.role,
          studentId: formData.studentId,
          userId: result.user?._id
        });
        
        // Show success message and redirect
        navigate('/dashboard', {
          state: {
            registrationSuccess: true,
            message: `Welcome to ${UNIVERSITY_NAME} IT Support System!`,
            userRole: formData.role,
            studentId: formData.studentId
          }
        });
      } else {
        throw new Error(result.error || 'Registration failed');
      }
      
    } catch (err) {
      console.error('❌ Registration error:', err);
      
      // Enhanced error handling
      let errorMessage = 'Registration failed. Please try again.';
      
      if (err.response) {
        const { status, data } = err.response;
        
        switch (status) {
          case 400:
            errorMessage = data?.message || 'Invalid registration data';
            break;
          case 409:
            if (data?.message?.includes('Student ID')) {
              errorMessage = 'This Student ID is already registered';
            } else {
              errorMessage = 'An account with this email already exists';
            }
            break;
          case 422:
            errorMessage = data?.message || 'Validation failed. Please check your inputs.';
            break;
          case 429:
            errorMessage = 'Too many registration attempts. Please try again later.';
            break;
          case 500:
            errorMessage = 'Server error. Please try again later.';
            break;
          default:
            errorMessage = data?.message || errorMessage;
        }
      } else if (err.code === 'ECONNABORTED') {
        errorMessage = 'Request timeout. Please check your connection.';
      } else if (err.message === 'Network Error') {
        errorMessage = 'Cannot connect to server. Check your internet connection.';
      }
      
      setError(errorMessage);
      
      // Log registration failure
      logSecurityEvent('registration_failed', {
        email: formData.email,
        error: err.message,
        status: err.response?.status
      });
      
    } finally {
      setLoading(false);
      setIsSubmitting(false);
    }
  };

  /**
   * Toggles password visibility
   */
  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  /**
   * Toggles confirm password visibility
   */
  const toggleConfirmPasswordVisibility = () => {
    setShowConfirmPassword(!showConfirmPassword);
  };

  /**
   * Handles role change with validation
   */
  const handleRoleChange = (role) => {
    setFormData(prev => ({
      ...prev,
      role,
      // Clear student-specific fields if role changes from student
      ...(prev.role === 'student' && role !== 'student' && { 
        studentId: '',
        program: '',
        campus: 'main',
        yearOfEntry: CURRENT_YEAR,
        status: 'R'
      }),
      // Clear department if changing to student
      ...(prev.role !== 'student' && role === 'student' && { 
        department: ''
      })
    }));
    
    // Clear role-specific validation errors
    setValidationErrors(prev => {
      const newErrors = { ...prev };
      delete newErrors.studentId;
      delete newErrors.program;
      delete newErrors.campus;
      delete newErrors.department;
      return newErrors;
    });
  };

  /**
   * Gets current role object
   */
  const getCurrentRole = () => {
    return roleOptions.find(role => role.value === formData.role) || roleOptions[0];
  };

  /**
   * Gets selected program object
   */
  const getSelectedProgram = () => {
    return programs.find(p => p.value === formData.program);
  };

  /**
   * Gets selected campus object
   */
  const getSelectedCampus = () => {
    return campuses.find(c => c.value === formData.campus);
  };

  // Get password strength info
  const strengthInfo = getPasswordStrengthInfo();

  // Check if form is disabled
  const isFormDisabled = loading || isSubmitting;

  // Get current role
  const currentRole = getCurrentRole();

  return (
    <>
      <Navbar />
      <div className="auth-container">
        <div className="auth-form">
          {/* Header */}
          <div className="auth-header">
            <div className="auth-logo">
              <svg className="logo-icon" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 2L3 7V12C3 16.97 7.03 21 12 21C16.97 21 21 16.97 21 12V7L12 2Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
                <path d="M12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12C9 13.6569 10.3431 15 12 15Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              <h2>Bugema University IT Support</h2>
            </div>
            <p className="auth-subtitle">Create your university account</p>
          </div>

          {/* Progress Bar */}
          <div className="progress-bar">
            <div 
              className="progress-fill" 
              style={{ width: `${formProgress}%` }}
              role="progressbar"
              aria-valuenow={formProgress}
              aria-valuemin="0"
              aria-valuemax="100"
            >
              <span className="progress-text">{formProgress}% Complete</span>
            </div>
          </div>

          {/* Error Message */}
          {error && (
            <div className="error-message" role="alert">
              <div className="error-icon">
                <svg viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                </svg>
              </div>
              <div className="error-content">
                <p>{error}</p>
              </div>
            </div>
          )}

          {/* Registration Form */}
          <form onSubmit={handleSubmit} className="register-form" noValidate>
            {/* Personal Information Section */}
            <div className="form-section">
              <h3 className="section-title">
                <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '20px', height: '20px' }}>
                  <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/>
                </svg>
                Personal Information
              </h3>
              
              <div className="form-group">
                <label htmlFor="username" className="form-label">
                  Full Name <span className="required">*</span>
                </label>
                <div className={`input-group ${validationErrors.username ? 'error' : ''}`}>
                  <div className="input-icon">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/>
                    </svg>
                  </div>
                  <input
                    ref={nameRef}
                    id="username"
                    name="username"
                    type="text"
                    autoComplete="name"
                    value={formData.username}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    placeholder="Enter your full name"
                    className="form-input"
                    aria-describedby={validationErrors.username ? "username-error" : undefined}
                    aria-required="true"
                  />
                </div>
                {validationErrors.username && (
                  <div id="username-error" className="error-text" role="alert">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                    {validationErrors.username}
                  </div>
                )}
              </div>
              
              <div className="form-group">
                <label htmlFor="email" className="form-label">
                  Bugema University Email <span className="required">*</span>
                </label>
                <div className={`input-group ${validationErrors.email ? 'error' : ''}`}>
                  <div className="input-icon">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"/>
                    </svg>
                  </div>
                  <input
                    id="email"
                    name="email"
                    type="email"
                    autoComplete="email"
                    value={formData.email}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    placeholder="name@bugemauniv.ac.ug"
                    className="form-input"
                    aria-describedby={validationErrors.email ? "email-error" : undefined}
                    aria-required="true"
                  />
                </div>
                {validationErrors.email && (
                  <div id="email-error" className="error-text" role="alert">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                    {validationErrors.email}
                  </div>
                )}
                <div className="info-note">
                  <div className="note-content">
                    <p>Use your official Bugema University email address</p>
                  </div>
                </div>
              </div>

              <div className="form-group">
                <label htmlFor="phone" className="form-label">
                  Phone Number (Uganda) <span className="required">*</span>
                </label>
                <div className={`input-group ${validationErrors.phone ? 'error' : ''}`}>
                  <div className="input-icon">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"/>
                    </svg>
                  </div>
                  <input
                    id="phone"
                    name="phone"
                    type="tel"
                    autoComplete="tel"
                    value={formData.phone}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    placeholder="07XXXXXXXX or 2567XXXXXXXX"
                    className="form-input"
                    aria-describedby={validationErrors.phone ? "phone-error" : undefined}
                    aria-required="true"
                  />
                </div>
                {validationErrors.phone && (
                  <div id="phone-error" className="error-text" role="alert">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                    {validationErrors.phone}
                  </div>
                )}
              </div>
            </div>

            {/* Account Type Section */}
            <div className="form-section">
              <h3 className="section-title">
                <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '20px', height: '20px' }}>
                  <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
                </svg>
                Account Type
              </h3>
              
              <div className="role-selection">
                {roleOptions.map(option => (
                  <label 
                    key={option.value} 
                    className={`role-option ${formData.role === option.value ? 'selected' : ''}`}
                    onClick={() => handleRoleChange(option.value)}
                  >
                    <input
                      type="radio"
                      name="role"
                      value={option.value}
                      checked={formData.role === option.value}
                      onChange={() => handleRoleChange(option.value)}
                      className="role-radio"
                      disabled={isFormDisabled}
                      aria-label={option.label}
                    />
                    <div className="role-content">
                      <span className="role-icon">{option.icon}</span>
                      <div className="role-info">
                        <span className="role-label">{option.label}</span>
                        <span className="role-description">{option.description}</span>
                        {option.requiresApproval && (
                          <span className="role-notice">
                            <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '14px', height: '14px', marginRight: '4px' }}>
                              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
                            </svg>
                            Requires approval
                          </span>
                        )}
                      </div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {/* Student-Specific Information */}
            {currentRole.showStudentFields && (
              <div className="form-section">
                <h3 className="section-title">
                  <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '20px', height: '20px' }}>
                    <path d="M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z"/>
                  </svg>
                  Academic Information
                </h3>
                
                {/* Program/Course Selection */}
                <div className="form-group">
                  <label htmlFor="program" className="form-label">
                    Program/Course <span className="required">*</span>
                  </label>
                  <div className={`input-group ${validationErrors.program ? 'error' : ''}`}>
                    <div className="input-icon">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M5 13.18v4L12 21l7-3.82v-4L12 17l-7-3.82zM12 3L1 9l11 6 9-4.91V17h2V9L12 3z"/>
                      </svg>
                    </div>
                    <select
                      id="program"
                      name="program"
                      value={formData.program}
                      onChange={handleChange}
                      disabled={isFormDisabled}
                      className="form-select"
                      aria-describedby={validationErrors.program ? "program-error" : undefined}
                      aria-required="true"
                    >
                      <option value="">Select your program</option>
                      {programs.map(program => (
                        <option key={program.value} value={program.value}>
                          {program.label} ({program.code})
                        </option>
                      ))}
                    </select>
                  </div>
                  {validationErrors.program && (
                    <div id="program-error" className="error-text" role="alert">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                      </svg>
                      {validationErrors.program}
                    </div>
                  )}
                </div>

                {/* Campus Selection */}
                <div className="form-group">
                  <label htmlFor="campus" className="form-label">
                    Campus <span className="required">*</span>
                  </label>
                  <div className={`input-group ${validationErrors.campus ? 'error' : ''}`}>
                    <div className="input-icon">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2L3 7V12C3 16.97 7.03 21 12 21C16.97 21 21 16.97 21 12V7L12 2Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      </svg>
                    </div>
                    <select
                      id="campus"
                      name="campus"
                      value={formData.campus}
                      onChange={handleChange}
                      disabled={isFormDisabled}
                      className="form-select"
                      aria-describedby={validationErrors.campus ? "campus-error" : undefined}
                      aria-required="true"
                    >
                      <option value="">Select your campus</option>
                      {campuses.map(campus => (
                        <option key={campus.value} value={campus.value}>
                          {campus.label} ({campus.code})
                        </option>
                      ))}
                    </select>
                  </div>
                  {validationErrors.campus && (
                    <div id="campus-error" className="error-text" role="alert">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                      </svg>
                      {validationErrors.campus}
                    </div>
                  )}
                </div>

                {/* Year of Entry and Status */}
                <div className="form-row">
                  <div className="form-group">
                    <label htmlFor="yearOfEntry" className="form-label">
                      Year of Entry <span className="required">*</span>
                    </label>
                    <div className="input-group">
                      <div className="input-icon">
                        <svg viewBox="0 0 24 24" fill="currentColor">
                          <path d="M9 11H7v2h2v-2zm4 0h-2v2h2v-2zm4 0h-2v2h2v-2zm2-7h-1V2h-2v2H8V2H6v2H5c-1.11 0-1.99.9-1.99 2L3 20c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 16H5V9h14v11z"/>
                        </svg>
                      </div>
                      <input
                        id="yearOfEntry"
                        name="yearOfEntry"
                        type="text"
                        value={formData.yearOfEntry}
                        onChange={handleChange}
                        disabled={isFormDisabled}
                        placeholder="YY (e.g., 22)"
                        maxLength="2"
                        className="form-input"
                        aria-required="true"
                      />
                    </div>
                  </div>

                  <div className="form-group">
                    <label htmlFor="status" className="form-label">
                      Student Status <span className="required">*</span>
                    </label>
                    <div className="input-group">
                      <div className="input-icon">
                        <svg viewBox="0 0 24 24" fill="currentColor">
                          <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/>
                        </svg>
                      </div>
                      <select
                        id="status"
                        name="status"
                        value={formData.status}
                        onChange={handleChange}
                        disabled={isFormDisabled}
                        className="form-select"
                        aria-required="true"
                      >
                        {studentStatusOptions.map(status => (
                          <option key={status.value} value={status.value}>
                            {status.label} ({status.value})
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                </div>

                {/* Student ID Input */}
                <div className="form-group">
                  <label htmlFor="studentId" className="form-label">
                    Student ID <span className="required">*</span>
                  </label>
                  <div className={`input-group ${validationErrors.studentId ? 'error' : ''}`}>
                    <div className="input-icon">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-5 14H4v-4h11v4zm0-5H4V9h11v4zm5 5h-4V9h4v9z"/>
                      </svg>
                    </div>
                    <input
                      id="studentId"
                      name="studentId"
                      type="text"
                      value={formData.studentId}
                      onChange={handleChange}
                      disabled={isFormDisabled}
                      placeholder="22/BIT/BU/R/0010"
                      className="form-input"
                      aria-describedby={validationErrors.studentId ? "studentId-error" : undefined}
                      aria-required="true"
                    />
                  </div>
                  {validationErrors.studentId && (
                    <div id="studentId-error" className="error-text" role="alert">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                      </svg>
                      {validationErrors.studentId}
                    </div>
                  )}
                  
                  {/* Student ID Format Guide */}
                  <div className="info-note">
                    <div className="note-content">
                      <p><strong>Student ID Format:</strong> YY/PROGRAM/CAMPUS/STATUS/NUMBER</p>
                      <p><strong>Example:</strong> 22/BIT/BU/R/0010</p>
                      <p>
                        <strong>Where:</strong> 
                        22 = Year of entry, 
                        BIT = Program code, 
                        BU = Campus code, 
                        R = Student status (R/H/E/W), 
                        0010 = Unique number
                      </p>
                    </div>
                  </div>
                  
                  {/* Auto-generated ID preview */}
                  {autoGeneratedStudentId && (
                    <div className="info-note success">
                      <div className="note-content">
                        <p><strong>Expected format based on your selection:</strong></p>
                        <code className="student-id-preview">{autoGeneratedStudentId}</code>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Staff/Non-Student Information */}
            {!currentRole.showStudentFields && (
              <div className="form-section">
                <h3 className="section-title">
                  <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '20px', height: '20px' }}>
                    <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V5h14v14zM7 10h2v7H7zm4-3h2v10h-2zm4-3h2v13h-2z"/>
                  </svg>
                  Staff Information
                </h3>
                
                <div className="form-group">
                  <label htmlFor="department" className="form-label">
                    Department <span className="required">*</span>
                  </label>
                  <div className={`input-group ${validationErrors.department ? 'error' : ''}`}>
                    <div className="input-icon">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M16 6l2.29 2.29-4.88 4.88-4-4L2 16.59 3.41 18l6-6 4 4 6.3-6.29L22 12V6z"/>
                      </svg>
                    </div>
                    <select
                      id="department"
                      name="department"
                      value={formData.department}
                      onChange={handleChange}
                      disabled={isFormDisabled}
                      className="form-select"
                      aria-describedby={validationErrors.department ? "department-error" : undefined}
                      aria-required="true"
                    >
                      <option value="">Select your department</option>
                      {departments.map(dept => (
                        <option key={dept.value} value={dept.value}>
                          {dept.label}
                        </option>
                      ))}
                    </select>
                  </div>
                  {validationErrors.department && (
                    <div id="department-error" className="error-text" role="alert">
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                      </svg>
                      {validationErrors.department}
                    </div>
                  )}
                </div>

                {/* Staff account note */}
                <div className="info-note warning">
                  <div className="note-icon">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                  </div>
                  <div className="note-content">
                    <strong>Staff Account Verification</strong>
                    <p>Staff, lecturer, and administrator accounts require verification by the IT department. You will receive an email notification once your account is approved.</p>
                  </div>
                </div>
              </div>
            )}

            {/* Security Section */}
            <div className="form-section">
              <h3 className="section-title">
                <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '20px', height: '20px' }}>
                  <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/>
                </svg>
                Account Security
              </h3>
              
              <div className="form-group">
                <label htmlFor="password" className="form-label">
                  Password <span className="required">*</span>
                </label>
                <div className={`input-group ${validationErrors.password ? 'error' : ''}`}>
                  <div className="input-icon">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/>
                    </svg>
                  </div>
                  <input
                    id="password"
                    name="password"
                    type={showPassword ? "text" : "password"}
                    autoComplete="new-password"
                    value={formData.password}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    placeholder="Create a strong password"
                    className="form-input"
                    aria-describedby={validationErrors.password ? "password-error" : undefined}
                    aria-required="true"
                  />
                  <button
                    type="button"
                    onClick={togglePasswordVisibility}
                    className="password-toggle"
                    disabled={isFormDisabled}
                    aria-label={showPassword ? "Hide password" : "Show password"}
                  >
                    {showPassword ? (
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 7c2.76 0 5 2.24 5 5 0 .65-.13 1.26-.36 1.83l2.92 2.92c1.51-1.26 2.7-2.89 3.43-4.75-1.73-4.39-6-7.5-11-7.5-1.4 0-2.74.25-3.98.7l2.16 2.16C10.74 7.13 11.35 7 12 7zM2 4.27l2.28 2.28.46.46C3.08 8.3 1.78 10.02 1 12c1.73 4.39 6 7.5 11 7.5 1.55 0 3.03-.3 4.38-.84l.42.42L19.73 22 21 20.73 3.27 3 2 4.27zM7.53 9.8l1.55 1.55c-.05.21-.08.43-.08.65 0 1.66 1.34 3 3 3 .22 0 .44-.03.65-.08l1.55 1.55c-.67.33-1.41.53-2.2.53-2.76 0-5-2.24-5-5 0-.79.2-1.53.53-2.2zm4.31-.78l3.15 3.15.02-.16c0-1.66-1.34-3-3-3l-.17.01z"/>
                      </svg>
                    ) : (
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"/>
                      </svg>
                    )}
                  </button>
                </div>
                
                {/* Password Strength Meter */}
                {formData.password && (
                  <div className="password-strength">
                    <div className="strength-meter">
                      <div 
                        className={`strength-bar ${strengthInfo.className}`}
                        style={{ width: `${passwordStrength}%` }}
                      ></div>
                    </div>
                    <div className="strength-info">
                      <span className="strength-label">Strength: {strengthInfo.label}</span>
                      <span className="strength-score">{passwordStrength}%</span>
                    </div>
                  </div>
                )}
                
                {validationErrors.password && (
                  <div id="password-error" className="error-text" role="alert">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                    {validationErrors.password}
                  </div>
                )}
                
                <div className="password-requirements">
                  <p><strong>Password requirements:</strong></p>
                  <ul>
                    <li className={formData.password.length >= 8 ? 'valid' : 'invalid'}>
                      At least 8 characters
                    </li>
                    <li className={/[A-Z]/.test(formData.password) ? 'valid' : 'invalid'}>
                      One uppercase letter
                    </li>
                    <li className={/[a-z]/.test(formData.password) ? 'valid' : 'invalid'}>
                      One lowercase letter
                    </li>
                    <li className={/[0-9]/.test(formData.password) ? 'valid' : 'invalid'}>
                      One number
                    </li>
                    <li className={/[^A-Za-z0-9]/.test(formData.password) ? 'valid' : 'invalid'}>
                      One special character
                    </li>
                  </ul>
                </div>
              </div>

              <div className="form-group">
                <label htmlFor="confirmPassword" className="form-label">
                  Confirm Password <span className="required">*</span>
                </label>
                <div className={`input-group ${validationErrors.confirmPassword ? 'error' : ''}`}>
                  <div className="input-icon">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/>
                    </svg>
                  </div>
                  <input
                    id="confirmPassword"
                    name="confirmPassword"
                    type={showConfirmPassword ? "text" : "password"}
                    autoComplete="new-password"
                    value={formData.confirmPassword}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    placeholder="Re-enter your password"
                    className="form-input"
                    aria-describedby={validationErrors.confirmPassword ? "confirmPassword-error" : undefined}
                    aria-required="true"
                  />
                  <button
                    type="button"
                    onClick={toggleConfirmPasswordVisibility}
                    className="password-toggle"
                    disabled={isFormDisabled}
                    aria-label={showConfirmPassword ? "Hide password" : "Show password"}
                  >
                    {showConfirmPassword ? (
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 7c2.76 0 5 2.24 5 5 0 .65-.13 1.26-.36 1.83l2.92 2.92c1.51-1.26 2.7-2.89 3.43-4.75-1.73-4.39-6-7.5-11-7.5-1.4 0-2.74.25-3.98.7l2.16 2.16C10.74 7.13 11.35 7 12 7zM2 4.27l2.28 2.28.46.46C3.08 8.3 1.78 10.02 1 12c1.73 4.39 6 7.5 11 7.5 1.55 0 3.03-.3 4.38-.84l.42.42L19.73 22 21 20.73 3.27 3 2 4.27zM7.53 9.8l1.55 1.55c-.05.21-.08.43-.08.65 0 1.66 1.34 3 3 3 .22 0 .44-.03.65-.08l1.55 1.55c-.67.33-1.41.53-2.2.53-2.76 0-5-2.24-5-5 0-.79.2-1.53.53-2.2zm4.31-.78l3.15 3.15.02-.16c0-1.66-1.34-3-3-3l-.17.01z"/>
                      </svg>
                    ) : (
                      <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"/>
                      </svg>
                    )}
                  </button>
                </div>
                {validationErrors.confirmPassword && (
                  <div id="confirmPassword-error" className="error-text" role="alert">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                    {validationErrors.confirmPassword}
                  </div>
                )}
              </div>
            </div>

            {/* Terms and Conditions */}
            <div className="form-section">
              <h3 className="section-title">
                <svg viewBox="0 0 24 24" fill="currentColor" style={{ width: '20px', height: '20px' }}>
                  <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V5h14v14zM17.99 9l-1.41-1.42-6.59 6.59-2.58-2.57-1.42 1.41 4 3.99z"/>
                </svg>
                Terms and Conditions
              </h3>
              
              <div className="form-group checkbox-group">
                <label className="checkbox-label">
                  <input
                    type="checkbox"
                    name="agreeToTerms"
                    checked={formData.agreeToTerms}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    className="checkbox-input"
                    aria-describedby={validationErrors.agreeToTerms ? "terms-error" : undefined}
                    aria-required="true"
                  />
                  <span className="checkbox-custom"></span>
                  <span className="checkbox-text">
                    I agree to Bugema University's{' '}
                    <Link to="/terms" target="_blank" className="link">
                      Terms of Service
                    </Link>
                    {' '}and{' '}
                    <Link to="/privacy" target="_blank" className="link">
                      Privacy Policy
                    </Link>
                    <span className="required">*</span>
                  </span>
                </label>
                {validationErrors.agreeToTerms && (
                  <div id="terms-error" className="error-text" role="alert">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/>
                    </svg>
                    {validationErrors.agreeToTerms}
                  </div>
                )}
              </div>
              
              <div className="form-group checkbox-group">
                <label className="checkbox-label">
                  <input
                    type="checkbox"
                    name="receiveNotifications"
                    checked={formData.receiveNotifications}
                    onChange={handleChange}
                    disabled={isFormDisabled}
                    className="checkbox-input"
                  />
                  <span className="checkbox-custom"></span>
                  <span className="checkbox-text">
                    I want to receive notifications about university announcements and system updates
                  </span>
                </label>
              </div>
              
              <div className="info-note">
                <div className="note-content">
                  <p><strong>Important Information:</strong></p>
                  <ul>
                    <li>You are responsible for maintaining the confidentiality of your account credentials</li>
                    <li>All account activities are monitored for security purposes</li>
                    <li>Misuse of the system may result in account suspension</li>
                    <li>By registering, you confirm that all information provided is accurate</li>
                  </ul>
                </div>
              </div>
            </div>
            
            {/* Submit Button */}
            <div className="form-group">
              <button
                type="submit"
                disabled={isFormDisabled}
                className={`auth-btn ${loading ? 'loading' : ''}`}
                aria-busy={loading}
              >
                {loading ? (
                  <>
                    <span className="spinner"></span>
                    Creating Account...
                  </>
                ) : (
                  'Create Bugema University Account'
                )}
              </button>
            </div>
          </form>
          
          {/* Footer */}
          <div className="auth-footer">
            <p className="auth-link">
              Already have an account?{' '}
              <Link 
                to="/login" 
                className="link"
                aria-disabled={isFormDisabled}
              >
                Login here
              </Link>
            </p>
            <p className="auth-version">
              Bugema University IT Support System v{process.env.REACT_APP_VERSION || '1.0.0'}
            </p>
          </div>

          {/* University Contact Information */}
          <div className="security-footer">
            <p className="security-notice">
              Need help with registration? Contact Bugema University IT Support:
            </p>
            <p className="security-contact">
              📧 <a href="mailto:itsupport@bugemauniv.ac.ug">itsupport@bugemauniv.ac.ug</a> • 
              📞 <a href="tel:+256392730294">+256 392 730 294</a> •
              📍 Main Campus, Luwero
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default Register;